# AutoEIT Automated Scoring System
## GSoC 2026 — HumanAI Foundation

This notebook implements an automated scoring system for the **Elicited Imitation Task (EIT)** — 
a research tool used to measure global language proficiency in second language learners.

### Approach
The scoring pipeline uses a **3-layer hybrid system**:

**Layer 1 — Rule-Based Scorer (transparent baseline)**
- Normalizes text by removing accents and punctuation
- Filters disfluencies and filler words (`um`, `uh`, `...`)
- Matches words using fuzzy matching (`rapidfuzz`) to handle spelling variations
- Uses Spanish stemming (`nltk SnowballStemmer`) to handle verb form differences
- Maps word match percentage to 0-4 scale

**Layer 2 — Semantic Similarity (ML signal)**
- Encodes stimulus and transcription using `paraphrase-multilingual-MiniLM-L12-v2`
- Computes cosine similarity in vector space
- Captures meaning preservation even when words differ completely

**Layer 3 — LLM Scorer (edge case handler)**
- Uses Groq (Llama 3.1 8b) with `temperature=0.0` for reproducible scoring
- Applies meaning-based rubric with Spanish linguistic understanding
- Handles disfluent speech, partial sentences, and mixed language
- Provides human-readable reasoning for every score

### Final Score Calculation
```
Final Score = (Rule Score × 0.4) + (LLM Score × 0.4) + (Similarity Score × 0.2)
```
- Rule-based and LLM get equal weight as primary scorers
- Semantic similarity acts as a supporting signal
- Score is clamped to 0-4 range

### Why This Approach
- **Transparency** — rule-based layer makes every scoring decision explainable
- **Consistency** — `temperature=0.0` ensures identical LLM scores on repeated runs, directly addressing the inconsistency problem stated in the AutoEIT2 proposal
- **Robustness** — 3 independent signals reduce overconfidence in edge cases
- **Multilingual** — all components handle Spanish natively

### Scoring Rubric (0-4 scale)
| Score | Meaning |
|---|---|
| 0 | No meaningful words reproduced, meaning completely lost |
| 1 | Very few words correct, meaning mostly lost |
| 2 | Some words correct, partial meaning preserved |
| 3 | Most words correct, meaning mostly preserved |
| 4 | All or nearly all words correct, meaning fully preserved |

In [1]:
import os
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"

from dotenv import load_dotenv
load_dotenv()

from preprocessor import load_all_files
from scorer import score_participant

print("All imports successful")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2689.20it/s]
BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

All imports successful

In [2]:
import glob

# Exclude the Info file
FILES = sorted([f for f in glob.glob('data/*.csv') if 'Info' not in f])

print(f"Found {len(FILES)} participant files:")
for f in FILES:
    print(f"  {f}")

sample = pd.read_csv(FILES[0], encoding='latin-1')
print(f"\nColumns found: {sample.columns.tolist()}")

Found 4 participant files:
  data\AutoEIT Sample Transcriptions for Scoring(38001-1A).csv
  data\AutoEIT Sample Transcriptions for Scoring(38002-2A).csv
  data\AutoEIT Sample Transcriptions for Scoring(38004-2A).csv
  data\AutoEIT Sample Transcriptions for Scoring(38006-2A).csv

Columns found: ['Sentence', 'Stimulus', 'Transcription Rater 1', 'Score']

In [3]:
dataframes = load_all_files(FILES)

print(f"\nLoaded {len(dataframes)} participant files")
print(f"Sentences per participant: {len(dataframes[0])}")
print("\nSample data — Participant 1:")
dataframes[0][['Sentence', 'Stimulus', 'Transcription Rater 1']].head(5)

Loaded 4 participant files
Sentences per participant: 30

Sample data — Participant 1:

,Sentence,Stimulus,Transcription Rater 1
0,1.0,Quiero cortarme el pelo,Quiero cortarme el pelo
1,2.0,El libro está en la mesa,El libro está en la mesa
2,3.0,El carro lo tiene Pedro,El carro lo tiene Pedro
3,4.0,El se ducha cada mañana,El se ducha cada mañana
4,5.0,¿Qué dice usted que va a hacer hoy?,Que dices ustedes se que van a hacer hoy?

## Example Scoring Walkthrough

Before running the full pipeline, let's see how a single sentence is scored.

The scorer:
1. Sends the stimulus and transcription to the LLM with the rubric
2. Computes semantic similarity using multilingual embeddings
3. Combines both into a final score

In [6]:
from scorer import score_utterance

# Pick one example
stimulus = "Dudo que sepa manejar muy bien"
transcription = "Dudo que sepa manajar bien"

result = score_utterance(stimulus, transcription)

print(f"Rule Score: {result['Rule_Score']}")
print(f"LLM_Score: {result['LLM_Score']}")
print(f"Semantic_Similarity: {result['Semantic_Similarity']}")
print(f"Score: {result['Score']}")
print(f"Divergence Flag: {result['Divergence_Flag']}")
print(f"LLM Reasoning: {result['Reasoning']}")

Rule Score: 3
LLM_Score: 3
Semantic_Similarity: 0.8548
Score: 3
Divergence Flag: False
LLM Reasoning: The learner reproduced most of the words correctly, with only a slight variation in the verb 'manejar' (manajar), but the overall meaning of the sentence is mostly preserved.

In [7]:
os.makedirs("output", exist_ok=True)

all_results = []

for df in dataframes:
    participant = df['Participant'].iloc[0]
    print(f"\nScoring: {participant}")
    
    scored_df = score_participant(df)
    all_results.append(scored_df)
    
    print(f"  Done. Total: {scored_df['Score'].sum()} / {len(scored_df) * 4}")

combined = pd.concat(all_results, ignore_index=True)
print("\n✅ All participants scored")

# Display results for each participant
for scored_df in all_results:
    participant = scored_df['Participant'].iloc[0]
    print(f"\n{'='*60}")
    print(f"Participant: {participant}")
    print(f"{'='*60}")
    display(scored_df[['Sentence', 'Stimulus', 'Transcription Rater 1', 
                 'Rule_Score', 'LLM_Score', 'Semantic_Similarity', 
                 'Score', 'Divergence_Flag', 'Reasoning']])

Scoring: AutoEIT Sample Transcriptions for Scoring(38001-1A)
  Scoring: Quiero cortarme el pelo...
  Scoring: El libro está en la mesa...
  Scoring: El carro lo tiene Pedro...
  Scoring: El se ducha cada mañana...
  Scoring: ¿Qué dice usted que va a hacer hoy?...
  Scoring: Dudo que sepa manejar muy bien...
  Scoring: Las calles de esta ciudad son muy anchas...
  Scoring: Puede que llueva mañana todo el día...
  Scoring: Las casas son muy bonitas pero caras...
  Scoring: Me gustan las películas que acaban bien...
  Scoring: El chico con el que yo salgo es español...
  Scoring: Después de cenar me fui a dormir tranquilo...
  Scoring: Quiero una casa en la que vivan mis animales...
  Scoring: A nosotros nos fascinan las fiestas grandiosas...
  Scoring: Ella sólo bebe cerveza y no come nada...
  Scoring: Me gustaría que el precio de las casas bajara...
  Scoring: Cruza a la derecha y después sigue todo recto...
  Scoring: Ella ha terminado de pintar su apartamento...
  Scoring: Me gustaría que empezara a hacer más calor pronto...
  Scoring: El niño al que se le murió el gato está triste...
  Scoring: Una amiga mía cuida a los niños de mi vecino...
  Scoring: El gato que era negro fue perseguido por el perro...
  Scoring: Antes de poder salir él tiene que limpiar su cuart...
  Scoring: La cantidad de personas que fuman ha disminuido...
  Scoring: Después de llegar a casa del trabajo tomé la cena...
  Scoring: El ladrón al que atrapó la policía era famoso...
  Scoring: Le pedí a un amigo que me ayudara con la tarea...
  Scoring: El examen no fue tan difícil como me habían dicho...
  Scoring: ¿Serías tan amable de darme el libro que está en l...
  Scoring: Hay mucha gente que no toma nada para el desayuno...
  Done. Total: 96 / 120

Scoring: AutoEIT Sample Transcriptions for Scoring(38002-2A)
  Scoring: Quiero cortarme el pelo...
  Scoring: El libro está en la mesa...
  Scoring: El carro lo tiene Pedro...
  Scoring: El se ducha cada mañana...
  Scoring: ¿Qué dice usted que va a hacer hoy?...
  Scoring: Dudo que sepa manejar muy bien...
  Scoring: Las calles de esta ciudad son muy anchas...
  Scoring: Puede que llueva mañana todo el día...
  Scoring: Las casas son muy bonitas pero caras...
  Scoring: Me gustan las películas que acaban bien...
  Scoring: El chico con el que yo salgo es español...
  Scoring: Después de cenar me fui a dormir tranquilo...
  Scoring: Quiero una casa en la que vivan mis animales...
  Scoring: A nosotros nos fascinan las fiestas grandiosas...
  Scoring: Ella sólo bebe cerveza y no come nada...
  Scoring: Me gustaría que el precio de las casas bajara...
  Scoring: Cruza a la derecha y después sigue todo recto...
  Scoring: Ella ha terminado de pintar su apartamento...
  Scoring: Me gustaría que empezara a hacer más calor pronto...
  Scoring: El niño al que se le murió el gato está triste...
  Scoring: Una amiga mía cuida a los niños de mi vecino...
  Scoring: El gato que era negro fue perseguido por el perro...
  Scoring: Antes de poder salir él tiene que limpiar su cuart...
  Scoring: La cantidad de personas que fuman ha disminuido...
  Scoring: Después de llegar a casa del trabajo tomé la cena...
  Scoring: El ladrón al que atrapó la policía era famoso...
  Scoring: Le pedí a un amigo que me ayudara con la tarea...
  Scoring: El examen no fue tan difícil como me habían dicho...
  Scoring: ¿Serías tan amable de darme el libro que está en l...
  Scoring: Hay mucha gente que no toma nada para el desayuno...
  Done. Total: 67 / 120

Scoring: AutoEIT Sample Transcriptions for Scoring(38004-2A)
  Scoring: Quiero cortarme el pelo...
  Scoring: El libro está en la mesa...
  Scoring: El carro lo tiene Pedro...
  Scoring: El se ducha cada mañana...
  Scoring: ¿Qué dice usted que va a hacer hoy?...
  Scoring: Dudo que sepa manejar muy bien...
  Scoring: Las calles de esta ciudad son muy anchas...
  Scoring: Puede que llueva mañana todo el día...
  Scoring: Las casas son muy bonitas pero caras...
  Scoring: Me gustan las películas que acaban bien...
  Scoring: El chico con el que yo salgo es español...
  Scoring: Después de cenar me fui a dormir tranquilo...
  Scoring: Quiero una casa en la que vivan mis animales...
  Scoring: A nosotros nos fascinan las fiestas grandiosas...
  Scoring: Ella sólo bebe cerveza y no come nada...
  Scoring: Me gustaría que el precio de las casas bajara...
  Scoring: Cruza a la derecha y después sigue todo recto...
  Scoring: Ella ha terminado de pintar su apartamento...
  Scoring: Me gustaría que empezara a hacer más calor pronto...
  Scoring: El niño al que se le murió el gato está triste...
  Scoring: Una amiga mía cuida a los niños de mi vecino...
  Scoring: El gato que era negro fue perseguido por el perro...
  Scoring: Antes de poder salir él tiene que limpiar su cuart...
  Scoring: La cantidad de personas que fuman ha disminuido...
  Scoring: Después de llegar a casa del trabajo tomé la cena...
  Scoring: El ladrón al que atrapó la policía era famoso...
  Scoring: Le pedí a un amigo que me ayudara con la tarea...
  Scoring: El examen no fue tan difícil como me habían dicho...
  Scoring: ¿Serías tan amable de darme el libro que está en l...
  Scoring: Hay mucha gente que no toma nada para el desayuno...
  Done. Total: 87 / 120

Scoring: AutoEIT Sample Transcriptions for Scoring(38006-2A)
  Scoring: Quiero cortarme el pelo...
  Scoring: El libro está en la mesa...
  Scoring: El carro lo tiene Pedro...
  Scoring: El se ducha cada mañana...
  Scoring: ¿Qué dice usted que va a hacer hoy?...
  Scoring: Dudo que sepa manejar muy bien...
  Scoring: Las calles de esta ciudad son muy anchas...
  Scoring: Puede que llueva mañana todo el día...
  Scoring: Las casas son muy bonitas pero caras...
  Scoring: Me gustan las películas que acaban bien...
  Scoring: El chico con el que yo salgo es español...
  Scoring: Después de cenar me fui a dormir tranquilo...
  Scoring: Quiero una casa en la que vivan mis animales...
  Scoring: A nosotros nos fascinan las fiestas grandiosas...
  Scoring: Ella sólo bebe cerveza y no come nada...
  Scoring: Me gustaría que el precio de las casas bajara...
  Scoring: Cruza a la derecha y después sigue todo recto...
  Scoring: Ella ha terminado de pintar su apartamento...
  Scoring: Me gustaría que empezara a hacer más calor pronto...
  Scoring: El niño al que se le murió el gato está triste...
  Scoring: Una amiga mía cuida a los niños de mi vecino...
  Scoring: El gato que era negro fue perseguido por el perro...
  Scoring: Antes de poder salir él tiene que limpiar su cuart...
  Scoring: La cantidad de personas que fuman ha disminuido...
  Scoring: Después de llegar a casa del trabajo tomé la cena...
  Scoring: El ladrón al que atrapó la policía era famoso...
  Scoring: Le pedí a un amigo que me ayudara con la tarea...
  Scoring: El examen no fue tan difícil como me habían dicho...
  Scoring: ¿Serías tan amable de darme el libro que está en l...
  Scoring: Hay mucha gente que no toma nada para el desayuno...
  Done. Total: 58 / 120

✅ All participants scored

============================================================
Participant: AutoEIT Sample Transcriptions for Scoring(38001-1A)
============================================================

,Sentence,Stimulus,Transcription Rater 1,Rule_Score,LLM_Score,Semantic_Similarity,Score,Divergence_Flag,Reasoning
0,1.0,Quiero cortarme el pelo,Quiero cortarme el pelo,4,4,1.0000,4,False,The learner fully preserved the meaning of the...
1,2.0,El libro está en la mesa,El libro está en la mesa,4,4,1.0000,4,False,The learner reproduced the prompt sentence exa...
2,3.0,El carro lo tiene Pedro,El carro lo tiene Pedro,4,4,1.0000,4,False,The learner fully preserved the meaning of the...
3,4.0,El se ducha cada mañana,El se ducha cada mañana,4,4,1.0000,4,False,The learner fully preserved the meaning of the...
4,5.0,¿Qué dice usted que va a hacer hoy?,Que dices ustedes se que van a hacer hoy?,3,2,0.9547,3,False,"The learner reproduced some words correctly, s..."
5,6.0,Dudo que sepa manejar muy bien,Dudo que sepa manajar bien,3,3,0.8548,3,False,The learner reproduced most of the words corre...
6,7.0,Las calles de esta ciudad son muy anchas,Las calles de esta cuidad son muy anchas,4,3,0.9567,4,False,The learner reproduced most of the words corre...
7,8.0,Puede que llueva mañana todo el día,Puede que lleva mañana todo el día,4,3,0.7493,3,False,The learner reproduced most of the words corre...
8,9.0,Las casas son muy bonitas pero caras,Las casas son muy bonitas pero muy cadas,3,3,0.8731,3,False,The learner preserved the meaning of the origi...
9,10.0,Me gustan las películas que acaban bien,Me gustan las peliculas que acaban bien,4,3,0.5403,3,False,The learner reproduced most of the words corre...
10,11.0,El chico con el que yo salgo es español,El chico con yo salgo ...um.. está bien,2,2,0.6090,2,False,The learner reproduced some words correctly ('...
11,12.0,Después de cenar me fui a dormir tranquilo,Despues de cenar me fui a dormir tranquilo,4,4,0.9627,4,False,The learner reproduced the prompt sentence wit...
12,13.0,Quiero una casa en la que vivan mis animales,Quiero una casa que vivan los animales,2,2,0.9793,2,False,"The learner reproduced some words correctly, s..."
13,14.0,A nosotros nos fascinan las fiestas grandiosas,A nosotros ..nos fascina los fiestas grandiosos,3,3,0.9819,3,False,The learner preserved the meaning of the origi...
14,15.0,Ella sólo bebe cerveza y no come nada,Ella solo bebe cerveza y no come nada,4,4,0.9993,4,False,The learner reproduced the prompt sentence wit...
15,16.0,Me gustaría que el precio de las casas bajara,Me gustaría que las precios de las casas bajaron,3,3,0.9869,3,False,The learner reproduced most of the words corre...
16,17.0,Cruza a la derecha y después sigue todo recto,Cruza a la derecha y sigue a la izquierda,2,2,0.9203,2,False,"The learner reproduced some words correctly, s..."
17,18.0,Ella ha terminado de pintar su apartamento,Ella ha terminado pintando su apartamento,3,3,0.9928,3,False,The learner preserved the meaning of the promp...
18,19.0,Me gustaría que empezara a hacer más calor pronto,Me gustaría se .. más calor,1,2,0.8690,2,False,The learner reproduced some words correctly ('...
19,20.0,El niño al que se le murió el gato está triste,El niño que se murió su gato es triste,3,3,0.9885,3,False,The learner preserved the meaning of the promp...
20,21.0,Una amiga mía cuida a los niños de mi vecino,una amiga de mio cuida su... niños de vecino,2,3,0.9066,3,False,The learner reproduced most of the words corre...
21,22.0,El gato que era negro fue perseguido por el perro,El gato que era negro era perseguido de(l) perro,3,3,0.9861,3,False,The learner mostly preserved the meaning of th...
22,23.0,Antes de poder salir él tiene que limpiar su c...,Antes de salir el tiene que limpiar su cuarto,4,3,0.9876,4,False,The learner reproduced most of the words corre...
23,24.0,La cantidad de personas que fuman ha disminuido,La cantidad de personas que fuman ha..desmenido,3,2,0.8384,3,False,"The learner reproduced some words correctly, s..."
24,25.0,Después de llegar a casa del trabajo tomé la cena,Despues de llegar a casa del trabajo...se...meh,2,2,0.5810,2,False,"The learner reproduced some words correctly, s..."
25,26.0,El ladrón al que atrapó la policía era famoso,El ladrón que atrapó la policia era famoso,3,3,0.9949,3,False,The learner reproduced most of the words corre...
26,27.0,Le pedí a un amigo que me ayudara con la tarea,Le pedí a un amigo que me ayudara con la tarea,4,4,1.0000,4,False,The learner fully reproduced the meaning of th...
27,28.0,El examen no fue tan difícil como me habían dicho,El examen no fue tan dificil como me decían,3,3,0.9930,3,False,The learner reproduced most of the words corre...
28,29.0,¿Serías tan amable de darme el libro que está ...,Serías tan amable pa'- darme el libro que está...,4,3,0.9821,4,False,The learner reproduced most of the words corre...
29,30.0,Hay mucha gente que no toma nada para el desayuno,Hay mucha genta que no to- toma nada para el d...,4,3,0.9895,4,False,The learner reproduced most of the words corre...

============================================================
Participant: AutoEIT Sample Transcriptions for Scoring(38002-2A)
============================================================

,Sentence,Stimulus,Transcription Rater 1,Rule_Score,LLM_Score,Semantic_Similarity,Score,Divergence_Flag,Reasoning
0,1.0,Quiero cortarme el pelo,Quiero cortarme el pelo,4,4,1.0000,4,False,The learner fully preserved the meaning of the...
1,2.0,El libro está en la mesa,El libro está en la mesa.,4,4,0.9980,4,False,The learner reproduced the prompt sentence exa...
2,3.0,El carro lo tiene Pedro,El carro tiene pelo.,2,1,0.3285,1,False,The learner reproduced very few words correctl...
3,4.0,El se ducha cada mañana,él se ducha cada mañana,4,4,0.9909,4,False,The learner reproduced the prompt sentence wit...
4,5.0,¿Qué dice usted que va a hacer hoy?,en que ustedes x uf x hacer hoy?,2,2,0.8503,2,False,"The learner reproduced some words correctly, s..."
5,6.0,Dudo que sepa manejar muy bien,dudo/tu no? sepiar exx muy bien,1,2,0.5456,2,False,"The learner reproduced some words correctly, s..."
6,7.0,Las calles de esta ciudad son muy anchas,La calles estén xxxx muy anchas.,1,2,0.9280,2,False,"The learner reproduced some words correctly, s..."
7,8.0,Puede que llueva mañana todo el día,Puede que mañana todo la día,3,2,0.7646,3,False,"The learner reproduced some words correctly, s..."
8,9.0,Las casas son muy bonitas pero caras,Las casas muy bonitos pero ... casas,3,2,0.7801,3,False,The learner partially preserved the meaning by...
9,10.0,Me gustan las películas que acaban bien,Me gustan las películas campan bien,3,2,0.9547,3,False,"The learner reproduced some words correctly, s..."
10,11.0,El chico con el que yo salgo es español,el chico con ... español,2,2,0.9555,2,False,"The learner reproduced some words correctly, i..."
11,12.0,Después de cenar me fui a dormir tranquilo,después de finar ... él dormir xxx,1,2,0.5972,2,False,The learner reproduced some words correctly ('...
12,13.0,Quiero una casa en la que vivan mis animales,Quiere una casa con animales,1,2,0.8507,2,False,The learner partially preserved the meaning by...
13,14.0,A nosotros nos fascinan las fiestas grandiosas,a nosotros fana-xxx fiestas grandinosas,2,3,0.8921,3,False,The learner reproduced most of the words corre...
14,15.0,Ella sólo bebe cerveza y no come nada,Ella xxx no beber querer,1,1,0.4679,1,False,The learner reproduced very few words correctl...
15,16.0,Me gustaría que el precio de las casas bajara,Me gusta el casa xxx...,1,2,0.4559,2,False,"The learner reproduced some words correctly, s..."
16,17.0,Cruza a la derecha y después sigue todo recto,en quises a la derecha xxx...,1,2,0.7156,2,False,The learner reproduced some words correctly ('...
17,18.0,Ella ha terminado de pintar su apartamento,Ella tiene termino xx apartamento,1,2,0.7494,2,False,"The learner reproduced some words correctly, s..."
18,19.0,Me gustaría que empezara a hacer más calor pronto,Me gusta que d-crxxx calor pranto,1,2,0.6567,2,False,"The learner reproduced some words correctly, s..."
19,20.0,El niño al que se le murió el gato está triste,El niño se murió el gato y triste,2,2,0.9718,2,False,"The learner reproduced some words correctly, s..."
20,21.0,Una amiga mía cuida a los niños de mi vecino,Una amigo que niña ha cuidado,1,2,0.6700,2,False,"The learner reproduced some words correctly, s..."
21,22.0,El gato que era negro fue perseguido por el perro,El gato negro se fuera el perro son,2,2,0.7527,2,False,"The learner reproduced some words correctly, s..."
22,23.0,Antes de poder salir él tiene que limpiar su c...,Antes de salir limpio.. el caso,2,1,0.6070,2,False,The learner reproduced very few words from the...
23,24.0,La cantidad de personas que fuman ha disminuido,la cantidad de las personas fe-xxx fumar,2,2,0.7737,2,False,"The learner reproduced some words correctly, s..."
24,25.0,Después de llegar a casa del trabajo tomé la cena,Después de llegar la casa pone cena,2,2,0.8476,2,False,"The learner reproduced some words correctly, s..."
25,26.0,El ladrón al que atrapó la policía era famoso,El xxx la policía es famoso,1,1,0.7214,1,False,The learner reproduced very few words correctl...
26,27.0,Le pedí a un amigo que me ayudara con la tarea,Le pedí un amigo con ayuda con mí tarea,2,2,0.9678,2,False,"The learner reproduced some words correctly, s..."
27,28.0,El examen no fue tan difícil como me habían dicho,El examen no es difícil cuando me xxx...,2,2,0.8190,2,False,"The learner reproduced some words correctly, i..."
28,29.0,¿Serías tan amable de darme el libro que está ...,El libro están en la mesa.,2,2,0.8296,2,False,The learner reproduced some words from the pro...
29,30.0,Hay mucha gente que no toma nada para el desayuno,Hay mucho gente no quiere desayuno,2,2,0.9308,2,False,"The learner reproduced some words correctly, s..."

============================================================
Participant: AutoEIT Sample Transcriptions for Scoring(38004-2A)
============================================================

,Sentence,Stimulus,Transcription Rater 1,Rule_Score,LLM_Score,Semantic_Similarity,Score,Divergence_Flag,Reasoning
0,1.0,Quiero cortarme el pelo,Quiero cortarme el pelo,4,4,1.0000,4,False,The learner fully preserved the meaning of the...
1,2.0,El libro está en la mesa,El libro está en la mesa,4,4,1.0000,4,False,The learner reproduced the prompt sentence exa...
2,3.0,El carro lo tiene Pedro,El carro tiene Pedro,3,3,0.9742,3,False,The learner preserved the meaning of the promp...
3,4.0,El se ducha cada mañana,El se ducha cada mañana,4,4,1.0000,4,False,The learner fully preserved the meaning of the...
4,5.0,¿Qué dice usted que va a hacer hoy?,¿Qué dices usted vas hacer hoy?,3,3,0.9888,3,False,The learner reproduced most of the words corre...
5,6.0,Dudo que sepa manejar muy bien,Dudo que sepa manejar muy bien,4,4,1.0000,4,False,The learner reproduced the prompt sentence exa...
6,7.0,Las calles de esta ciudad son muy anchas,Las calles de esta ciudad es muy anchas,3,3,0.9997,3,False,The learner reproduced most of the words corre...
7,8.0,Puede que llueva mañana todo el día,Pueda que llueva mañana todo día,3,3,0.9792,3,False,The learner reproduced most of the words corre...
8,9.0,Las casas son muy bonitas pero caras,Las casas son muy bonitas para caras,3,3,0.8431,3,False,The learner preserved the meaning of the origi...
9,10.0,Me gustan las películas que acaban bien,Mis gus..Me gustas las películas que cada bien,3,2,0.9162,3,False,"The learner reproduced some words correctly, s..."
10,11.0,El chico con el que yo salgo es español,El chico con esolago(es yo algo?) es español,3,2,0.9535,3,False,"The learner reproduced some words correctly, s..."
11,12.0,Después de cenar me fui a dormir tranquilo,Después de cenar fui a dormir tranquilo,3,3,0.9972,3,False,The learner reproduced most of the words corre...
12,13.0,Quiero una casa en la que vivan mis animales,Queda una ca..Quiere una casa en queda mis ani...,2,2,0.7777,2,False,"The learner reproduced some words correctly, s..."
13,14.0,A nosotros nos fascinan las fiestas grandiosas,A nosotros fascinmas festivales,1,2,0.8282,2,False,"The learner reproduced some words correctly, s..."
14,15.0,Ella sólo bebe cerveza y no come nada,Ella sólo cerveza y como nada,3,2,0.8409,3,False,"The learner reproduced some words correctly, s..."
15,16.0,Me gustaría que el precio de las casas bajara,Me gustaría que los precios de la casa bajara,3,3,0.9873,3,False,The learner reproduced most of the words corre...
16,17.0,Cruza a la derecha y después sigue todo recto,Sigue a la derecha y cruzo a la directo..y siq...,3,3,0.8197,3,False,The learner mostly preserved the meaning of th...
17,18.0,Ella ha terminado de pintar su apartamento,Ella se terminar pintar su apartamento,3,2,0.9778,3,False,"The learner reproduced some words correctly, s..."
18,19.0,Me gustaría que empezara a hacer más calor pronto,Me gustaría hacer..xx calores pronto,2,2,0.7829,2,False,"The learner reproduced some words correctly, s..."
19,20.0,El niño al que se le murió el gato está triste,El niño que se murió su gato es triste,3,3,0.9885,3,False,The learner preserved the meaning of the promp...
20,21.0,Una amiga mía cuida a los niños de mi vecino,Una amiga mía cuidado a los vecinos,3,2,0.7777,3,False,"The learner reproduced some words correctly, s..."
21,22.0,El gato que era negro fue perseguido por el perro,El gato que es negro... [cough]...,2,2,0.6656,2,False,"The learner reproduced some words correctly, s..."
22,23.0,Antes de poder salir él tiene que limpiar su c...,Antes de salir tienes xxx cu-cuarto,1,2,0.4395,2,False,"The learner reproduced some words correctly, s..."
23,24.0,La cantidad de personas que fuman ha disminuido,La cantidad de personas que fu-han fumado se d...,3,2,0.8261,3,False,"The learner reproduced some words correctly, s..."
24,25.0,Después de llegar a casa del trabajo tomé la cena,Después de llegar a-de trabajo cena a mi casa,3,2,0.9313,3,False,"The learner reproduced some words correctly, s..."
25,26.0,El ladrón al que atrapó la policía era famoso,La ladrón que atropó la policía es famoso,2,3,0.9872,3,False,The learner reproduced most of the words corre...
26,27.0,Le pedí a un amigo que me ayudara con la tarea,Le pedí un amigo que me ayuda con la tarea,4,3,0.9919,4,False,The learner reproduced most of the words corre...
27,28.0,El examen no fue tan difícil como me habían dicho,El examen no ..a..va a..fue a tan difícil,2,2,0.5787,2,False,"The learner reproduced some words correctly, s..."
28,29.0,¿Serías tan amable de darme el libro que está ...,Sales de donde está mi libro en está mesa,1,1,0.7747,1,False,The learner reproduced very few words correctl...
29,30.0,Hay mucha gente que no toma nada para el desayuno,Hay mucha gente que no toma tiempo para desayuno,3,2,0.9015,3,False,"The learner reproduced some words correctly, b..."

============================================================
Participant: AutoEIT Sample Transcriptions for Scoring(38006-2A)
============================================================

,Sentence,Stimulus,Transcription Rater 1,Rule_Score,LLM_Score,Semantic_Similarity,Score,Divergence_Flag,Reasoning
0,1.0,Quiero cortarme el pelo,Quiero cortarme mi pelo,3,3,0.9965,3,False,The learner reproduced most of the words corre...
1,2.0,El libro está en la mesa,El libro [pause] está en la mesa,4,3,0.8965,4,False,The learner reproduced most of the words corre...
2,3.0,El carro lo tiene Pedro,E-[gibberish] perro,0,1,0.2750,1,False,"The learner reproduced very few words correct,..."
3,4.0,El se ducha cada mañana,El se lucha cada mañana,3,2,0.5281,2,False,"The learner reproduced some words correctly, b..."
4,5.0,¿Qué dice usted que va a hacer hoy?,¿Qué [gibberish] que vas estoy?,1,1,0.5088,1,False,The learner reproduced very few words correctl...
5,6.0,Dudo que sepa manejar muy bien,Dudo que sepa ma-mastar tan bien (tambien?),2,3,0.6070,2,False,The learner reproduced most of the words corre...
6,7.0,Las calles de esta ciudad son muy anchas,Las calles..es-[gibberish]...,0,1,0.5222,1,False,The learner reproduced very few words correctl...
7,8.0,Puede que llueva mañana todo el día,Puede xxx mañana de todo día,2,2,0.7224,2,False,"The learner reproduced some words correctly, s..."
8,9.0,Las casas son muy bonitas pero caras,A las casa es mu-son bonitas,1,2,0.6584,2,False,"The learner reproduced some words correctly, s..."
9,10.0,Me gustan las películas que acaban bien,Me gusta las películas que x bien,3,2,0.9567,3,False,"The learner reproduced some words correctly, s..."
10,11.0,El chico con el que yo salgo es español,El chico con es el algo (xxx?) es español,3,2,0.9216,3,False,The learner partially preserved the meaning by...
11,12.0,Después de cenar me fui a dormir tranquilo,Después de fenar mi fui a tranquilo,2,2,0.6276,2,False,"The learner reproduced some words correctly, s..."
12,13.0,Quiero una casa en la que vivan mis animales,Quienen que en el casa ...muchos animales,1,2,0.6632,2,False,The learner reproduced some words from the pro...
13,14.0,A nosotros nos fascinan las fiestas grandiosas,A nosotros fanimos [pause] fiestas grandiosas,2,3,0.9066,3,False,The learner reproduced most of the words corre...
14,15.0,Ella sólo bebe cerveza y no come nada,Ella bebidas cerviamos y no comidas,2,2,0.6103,2,False,"The learner reproduced some words correctly, s..."
15,16.0,Me gustaría que el precio de las casas bajara,Me gustaría ser..ella...mhh..,0,1,0.0816,0,False,The learner reproduced very few words from the...
16,17.0,Cruza a la derecha y después sigue todo recto,Cruze a la derecha de siguelo,2,2,0.8631,2,False,"The learner reproduced some words correctly, s..."
17,18.0,Ella ha terminado de pintar su apartamento,Ella terminado pintar a sus apartmento,2,2,0.9788,2,False,"The learner reproduced some words correctly, s..."
18,19.0,Me gustaría que empezara a hacer más calor pronto,Me gustaría se..[pause] xxx pronto,1,2,0.3716,1,False,The learner reproduced some words correctly ('...
19,20.0,El niño al que se le murió el gato está triste,El niño se murió el gato es muy triste,2,2,0.9836,2,False,"The learner reproduced some words correctly, s..."
20,21.0,Una amiga mía cuida a los niños de mi vecino,Una mía amiga cuidado a sus niños,2,3,0.8767,3,False,The learner reproduced most of the words corre...
21,22.0,El gato que era negro fue perseguido por el perro,El gato-el gato quien era el nego de perro,2,1,0.6466,2,False,The learner reproduced very few words correctl...
22,23.0,Antes de poder salir él tiene que limpiar su c...,Antes de podai e salir..[pause] antes de xxx,0,2,0.4144,1,True,The learner reproduced some words from the pro...
23,24.0,La cantidad de personas que fuman ha disminuido,A la cantan... [pause] muy a xxx,0,0,0.1571,0,False,The learner's utterance does not contain any m...
24,25.0,Después de llegar a casa del trabajo tomé la cena,Después de llegar [pause] al trabajo...,1,2,0.5202,2,False,"The learner reproduced some words correctly, i..."
25,26.0,El ladrón al que atrapó la policía era famoso,X- ladróna(?)de policio que es famoso,1,2,0.7845,2,False,"The learner reproduced some words correctly, s..."
26,27.0,Le pedí a un amigo que me ayudara con la tarea,Que ped-x una amigo [pause] a su tarea,1,2,0.7346,2,False,"The learner reproduced some words correctly, s..."
27,28.0,El examen no fue tan difícil como me habían dicho,El examen no difícil.. [pause]... [gibberish],1,2,0.5889,2,False,The learner reproduced some words from the pro...
28,29.0,¿Serías tan amable de darme el libro que está ...,El libro que está en la mesa,2,3,0.8260,3,False,The learner reproduced most of the words from ...
29,30.0,Hay mucha gente que no toma nada para el desayuno,A mucha gente xxx...,0,2,0.3027,1,True,The learner reproduced some words from the pro...

In [8]:
print("===== SCORING SUMMARY =====\n")

summary_data = []

for scored_df in all_results:
    participant = scored_df['Participant'].iloc[0]
    total = scored_df['Score'].sum()
    maximum = len(scored_df) * 4
    pct = round((total / maximum) * 100, 1)
    avg_sim = scored_df['Semantic_Similarity'].mean()
    flagged = scored_df['Divergence_Flag'].sum()
    
    summary_data.append({
        'Participant': participant,
        'Score': f"{total}/{maximum}",
        'Percentage': f"{pct}%",
        'Avg Similarity': round(avg_sim, 4),
        'Divergent Sentences': flagged
    })

summary_df = pd.DataFrame(summary_data)
summary_df

===== SCORING SUMMARY =====

,Participant,Score,Percentage,Avg Similarity,Divergent Sentences
0,AutoEIT Sample Transcriptions for Scoring(3800...,96/120,80.0%,0.9159,0
1,AutoEIT Sample Transcriptions for Scoring(3800...,67/120,55.8%,0.7791,0
2,AutoEIT Sample Transcriptions for Scoring(3800...,87/120,72.5%,0.8843,0
3,AutoEIT Sample Transcriptions for Scoring(3800...,58/120,48.3%,0.6510,2

## Evaluation of Output

### How I validated the scores:
- **Consistency** — `temperature=0.0` ensures identical LLM scores on repeated runs, 
  directly addressing the inconsistency problem stated in the AutoEIT2 proposal
- **3-layer cross validation** — Rule-based, semantic similarity, and LLM scores are 
  computed independently. High divergence between layers flags sentences for human review
- **Fuzzy + stem matching** — Rule-based layer uses `rapidfuzz` and Spanish stemming 
  to handle spelling variations and verb forms, making word matching more accurate than 
  exact string comparison
- **Multilingual embeddings** — `paraphrase-multilingual-MiniLM-L12-v2` is specifically 
  trained for non-English languages, avoiding cross-lingual bias in similarity scoring

### Limitations:
- Without ground truth human scores, absolute accuracy cannot be measured — 
  divergence flagging is used as a proxy for uncertain cases
- Rule-based scorer may underperform on sentences with heavy paraphrasing or 
  synonyms since it relies on word-level matching
- LLM may occasionally misinterpret highly disfluent utterances with incomplete 
  sentence fragments
- Fuzzy matching threshold (80%) is heuristic — optimal threshold may vary 
  across proficiency levels